### ISSUE TITLE
XCFramework wont compile

### ISSUE THREAD

**Issue by yusufoos** [pivo-inc/pivo-pro-sdk-testapp-ios#2]
<img width="494" alt="Screen Shot 2021-10-16 at 10 18 20 AM" src="https://user-images.githubusercontent.com/1316153/137596476-89aaaba9-076e-44bd-8ed5-b5e3ceea8c71.png">

I believe the root of the issue is that there is a class `PivoProSDK` that has the same name as the module `PivoProSDK`

I was able to fix this with the workaround described here:
https://developer.apple.com/forums/thread/123253

But the real fix would be to make sure the the module name isn't conflicting with a class name.

**Comment by tuando3i** [comment]
Thanks @yusufoos for your suggestion. We will fix this issue in the next version.

**Comment by tuando3i** [comment]
@yusufoos We have fixed this bug in the latest version by changing `PivoProSDK` to `PivoSDK`. Please check it out
