### ISSUE TITLE
Pivo SDK does not responding when multiple commands are called.

### ISSUE THREAD

**Issue by yusufoos** [pivo-inc/pivo-pro-sdk-testapp-ios#3]
I've found that the PivoSDK ignores futures calls if you currently have one in flight.

Repro Scenario:
Call two PivoSDK methods together
`pivoSDK.requestBatteryLevel()`
`pivoSDK.turnLeft(angle: 60)`

Expected Result:
Pivo returns battery and then turns left

Actual Result:
Pivo returns battery and does _not_ turn left

This is particularly bad because update tracking is called every frame and frequently blocks any other calls to pivoSDK
`pivoSDK.updateTracking(image: image)`

@tuando3i

**Comment by yusufoos** [comment]
@tuando3i Any updates or ETA on this issue?
I'd be happy to help if you can give me access as a collaborator.

**Comment by 3i-kevin** [comment]
Hello @yusufoos , the pod has bandwidth limitation regarding how many commands it can receive & execute. In general, the pod can handle about 20 commands per second well. The SDK will be updated later to handle the commands from app and put them in a queue. However, in the meantime, please put a 50ms delay in your app between 2 commands. If it doesn't work, please let us know.

**Comment by yusufoos** [comment]
@nxt-kevin Thanks for the detailed reply, I've implemented your workaround and it's working great for me.
