### ISSUE TITLE
M1 Processor Issue

### ISSUE THREAD

**Issue by jayeshtejwani8055** [pivo-inc/pivo-pro-sdk-testapp-ios#4]
Hello Pivo Team
I used to work on MacBook Pro (Intel processor) where my pivot integration was working fine.
Just upgraded to MacBook Pro (M1 Processor) so I am facing issue building pivo.

I posted my error at developer.apple.com and a representative from apple answered me back on that thread.

// Answer from apple
"The real issue here is that pre-built binary libraries are required to be built with Library Evolution, as I stated. The compiler versions error is an example of a symptom that appears when this requirement is not met. If this library is from a vendor, please follow up with them about getting a version with Library Evolution enabled inside of an XCFramework."

![Screenshot 2022-02-09 at 10 50 46 AM](https://user-images.githubusercontent.com/86184328/153126899-342b1a5a-9999-4039-a242-fd35b55bda42.png)
![Screenshot 2022-02-09 at 10 50 50 AM](https://user-images.githubusercontent.com/86184328/153126913-d7e90e90-bace-4eda-8c09-6bd780a32a1a.png)

**Comment by tuando3i** [comment]
Hi @jayeshtejwani8055 , from the error log, it seems like your XCode version is not the latest version which has been using to build the PivoSDK. Can you update your XCode and try to build again? Thanks
